import React from "react";
import Head from "next/head";
import Menu from "./Menu";
import LoginMenu from "./Menu/LoginMenu";

const Layout = ({children}) => {
    return(
        <div>
            <Head>
                <title >
                    Fashion Design
                </title>

                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="./../public/favicon.ico" sizes="16x16"/>
            </Head>
            <main>
                <LoginMenu/>
                <Menu/>
                <h1>hello </h1>
                {children}
            </main>
        </div>
    )
};

export default Layout;
